name: libaribb25 build test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - './.github/workflows/**.yml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pwd
      run: pwd
    - name: dependencies
      run: sudo apt install libpcsclite-dev 
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
